### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by orkhanfarmanli** [CodeAcademyLab/DanaParking#2]
Readme file-ı materialize-ındı. Onu dəyişib özünüzünkü edin :)

**Comment by ro6ka** [comment]
reade neiniriy =)?

**Comment by CodeAcademyTeam** [comment]
Roska lahiyenin umumi izahatı ve kimler iştirak edirse onların github profillerini add ele zehmet olmasa readme faylına

**Comment by ro6ka** [comment]
окей =)
